name: shared

services:
  redis:
    container_name: redis
    image: docker.io/bitnami/redis
    restart: always
    networks:
      - shared_network
    ports:
      - "6379:6379"
    environment:
      TZ: ${TZ}
      REDIS_PASSWORD: ${REDIS_PASSWORD}
      REDIS_VOLUME_DIR: /redis
    volumes:
      - ${REDIS_DATA_LOCATION}/:/redis/data

networks:
  shared_network:
    name: shared_network
    driver: bridge
