name: shared

services:
  redis:
    container_name: redis
    image: docker.io/redis:alpine
    restart: always
    networks:
      - shared_network
    ports:
      - "6379:6379"
    environment:
      TZ: ${TZ}
    volumes:
      - ${REDIS_DATA_LOCATION}/:/data
    command:
      [
        "redis-server",
        "--requirepass",
        "$${REDIS_PASSWORD:?REDIS_PASSWORD variable is not set}"
      ]

networks:
  shared_network:
    name: shared_network
    driver: bridge
