name: shared

services:
  redis:
    container_name: redis
    image: docker.io/bitnami/redis
    restart: always
    networks:
      - shared_network
    ports:
      - "6379:6379"
    environment:
      TZ: ${TZ}
      REDIS_VOLUME_DIR: /redis
      REDIS_PASSWORD: ${REDIS_PASSWORD}
    volumes:
      - ${REDIS_DATA_LOCATION}/:/redis/data

  postgres:
    container_name: postgres
    image: postgres:latest
    restart: always
    shm_size: 128mb
    networks:
      - shared_network
    ports:
      - "5432:5432"
    environment:
      TZ: ${TZ}
      POSTGRES_INITDB_ARGS: '--data-checksums'
      POSTGRES_PASSWORD: ${POSTGRES_SU_PASSWORD}
      POSTGRES_USER: $POSTGRES_SU_USERNAME}
      POSTGRES_DB: ${POSTGRES_SU_DATABASE_NAME}
    volumes:
      - ${POSTGRES_DATA_LOCATION}:/var/lib/postgresql/data/

networks:
  shared_network:
    name: shared_network
    driver: bridge
