name: shared

services:
  redis:
    container_name: redis
    image: docker.io/bitnami/redis
    restart: always
    networks:
      - shared_network
    ports:
      - "6379:6379"
    environment:
      TZ: ${TZ}
      REDIS_VOLUME_DIR: /redis
      REDIS_PASSWORD: ${REDIS_PASSWORD}
    volumes:
      - ${REDIS_DATA_LOCATION}/:/redis/data

  postgres:
    container_name: postgres
    image: postgres:latest
    restart: always
    shm_size: 128mb
    networks:
      - shared_network
    ports:
      - "5432:5432"
    environment:
      TZ: ${TZ}
      POSTGRES_INITDB_ARGS: '--data-checksums'
      POSTGRES_USER: ${POSTGRES_SU_USERNAME}
      POSTGRES_PASSWORD: ${POSTGRES_SU_PASSWORD}
      POSTGRES_DB: ${POSTGRES_SU_DATABASE_NAME}
    volumes:
      - ${POSTGRES_DATA_LOCATION}:/var/lib/postgresql/data/

  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4
    labels:
      - dev.orbstack.domains=pgadmin.local
    depends_on:
      - postgres
    restart: always
    networks:
      - shared_network
    ports:
      - "8888:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_PASSWORD}
    volumes:
      - ${PGADMIN_DATA_LOCATION}:/var/lib/pgadmin/

  prometheus:
    container_name: prometheus
    image: prom/prometheus:latest
    labels:
      - dev.orbstack.domains=prometheus.local
    restart: always
    networks:
      - shared_network
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
      - ${PROMETHEUS_DATA_LOCATION}:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/usr/share/prometheus/console_libraries'
      - '--web.console.templates=/usr/share/prometheus/consoles'

  grafana:
    container_name: grafana
    image: grafana/grafana-oss:latest
    labels:
      - dev.orbstack.domains=grafana.local
    restart: always
    networks:
      - shared_network
    ports:
      - '3000:3000'
    volumes:
      - ${GRAFANA_DATA_LOCATION}:/var/lib/grafana
    depends_on:
      - prometheus

networks:
  shared_network:
    name: shared_network
    driver: bridge
